export {default as Header} from './Header/Header'
export {default as Survey} from  './Survey/Survey'
export {default as Footer} from './Footer/Footer'
export {default as Login} from './Login/Login'
export {default as Chess} from './Chess/Board'
export {default as Admin} from './AdminPanel/Admin'
